version: "3.4"
services:
  ################################################################
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    network_mode: bridge
    environment:
      - TZ=Europe/Moscow
      - PUID=1027
      - PGID=100
    volumes:
      - /volume1/docker/jackett/config:/config
      - /volume1/docker/jackett/downloads:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped

  ###############################################################
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=Europe/Moscow
      - PUID=1027
      - PGID=100
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/docker/radarr/downloads:/downloads
      - /volume1/media:/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  ###############################################################
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: bridge
    environment:
      - TZ=Europe/Moscow
      - PUID=1027
      - PGID=100
    restart: unless-stopped

  ###############################################################
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8068
      - PUID=1027
      - PGID=100
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume1/media:/movies
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8068:8068
    restart: unless-stopped

  ###############################################################
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=Europe/Moscow
      - PUID=1027
      - PGID=100
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/docker/sonarr/downloads:/downloads
      - /volume1/media:/movies
    ports:
      - 8989:8989
    restart: unless-stopped

  ###############################################################
  gramarrru:
    image: memodota/gramarrru
    container_name: gramarrru
    environment:
      - PUID=1027
      - PGID=100
    depends_on:
      - sonarr
      - radarr
    volumes:
      - /volume1/docker/gramarr/config.json:/config/config.json
    restart: unless-stopped
