services:
  antizapret-vpn:
    container_name: antizapret-vpn
    image: qmcgaw/gluetun
    network_mode: bridge
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun:rwm
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      TZ: Europe/Moscow
      PUID: 1027
      PGID: 100
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    ports:
      - 8096:8096 #jellyfin
      - 5055:5055 #jellyseerr
      - 6881:6881 #qbittorrent
      - 6881:6881/udp
      - 8068:8068
      - 8989:8989 #sonarr
      - 7878:7878 #radarr
      - 8191:8191 #flasesolver
      - 9117:9117 #jackett
    volumes:
      - /mnt/hdd/torrents/gluetun/wireguard/wg0.conf:/gluetun/wireguard/wg0.conf # Путь для конфигурации или логов

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    network_mode: service:antizapret-vpn
    depends_on:
      - antizapret-vpn
    environment:
      - TZ=Europe/Moscow
      - PUID=1027
      - PGID=100
    volumes:
      - /mnt/hdd/torrents/jackett/config:/config
      - /mnt/hdd/torrents/jackett/downloads:/downloads
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:antizapret-vpn
    environment:
      - WEBUI_PORT=8068
      - PUID=1027
      - PGID=100
    volumes:
      - /mnt/hdd/torrents/qbittorrent/config:/config
      - /mnt/hdd/torrents/media:/media
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:antizapret-vpn
    environment:
      - PUID=1027
      - PGID=100
    volumes:
      - /mnt/hdd/torrents/sonarr/config:/config
      - /mnt/hdd/torrents/sonarr/downloads:/downloads
      - /mnt/hdd/torrents/media:/meida
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:antizapret-vpn
    environment:
      - PUID=1027
      - PGID=100
    volumes:
      - /mnt/hdd/torrents/radarr/config:/config
      - /mnt/hdd/torrents/radarr/downloads:/downloads
      - /mnt/hdd/torrents/media:/media
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:antizapret-vpn
    depends_on:
      - antizapret-vpn
    environment:
      - TZ=Europe/Moscow
      - PUID=1027
      - PGID=100
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: service:antizapret-vpn
    environment:
      - TZ=Europe/Moscow
      - PUID=1027
      - PGID=100
    volumes:
      - /mnt/hdd/torrents/jellyfin/config:/config
      - /mnt/hdd/torrents/media:/media
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:2.2.3
    container_name: jellyseerr
    network_mode: service:antizapret-vpn
    environment:
      - TZ=Europe/Moscow
      - PUID=1027
      - PGID=100
    volumes:
      - /mnt/hdd/torrents/jellyseerr/config:/app/config
    restart: unless-stopped
